# Generated by Django 3.2.15 on 2024-02-28 06:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя заказа')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия пользователя заказа')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес для заказа')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер телефона')),
                ('quantity', models.SmallIntegerField(db_index=True, default=0, verbose_name='Кол-во заказа')),
                ('order_date', models.DateField(help_text='Дата заказа', verbose_name='Дата заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
