# Generated by Django 3.2.15 on 2024-02-28 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_userorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Дата заказа', verbose_name='Дата заказа'),
        ),
    ]
