# Generated by Django 3.2.15 on 2024-03-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20240301_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstate',
            options={'verbose_name': 'Состояние заказа', 'verbose_name_plural': 'Заказы из корзины'},
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='surname',
            new_name='lastname',
        ),
    ]
