# Generated by Django 3.2.15 on 2024-03-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240312_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_states', to='foodcartapp.userorder', verbose_name='заказ'),
        ),
    ]
