# Generated by Django 3.2.15 on 2024-03-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderstate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstate',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
            preserve_default=False,
        ),
    ]
