# Generated by Django 3.2.15 on 2024-03-19 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_rename_cost_orderstate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
        ),
    ]
