# Generated by Django 3.2.15 on 2024-03-20 09:00
from django.db import migrations
from django.db.models import F


def calculate_price(apps, schema_editor):
    """
    В миграциях Django ни в коем случае нельзя использовать код из models.py
     и прочих файлов проекта. Миграции делают изолированными и самодостаточными,
     чтобы их можно было запустить даже год спустя, когда от старого кода
     в проекте не останется ничего.
    Но ведь дата-миграциям нужны модели данных, тогда откуда их взять?
     В Django эта проблема решается через apps.get_model().
     Эта функция не возвращает последнюю актуальную модель данных, а воспроизводит ту
     старую, для которой миграция и писалась когда-то давно."
    """
    OrderState = apps.get_model("foodcartapp", "OrderState")

    orders = OrderState.objects.prefetch_related("product")
    # через итератор чтобы обработать большие объемы данных
    # и чтобы отключить кэширование https://blog.etianen.com/blog/2013/06/08/django-querysets/
    for order in orders.iterator():
        order.cost = F("product__price") * order.quantity
        order.save()



class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_orderstate_price'),
    ]

    operations = [
        migrations.RunPython(calculate_price)
    ]
