# Generated by Django 3.2.15 on 2024-03-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_orderstate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Заказ выполнен'), (0, 'Необработанный'), (1, 'Принят в работу'), (2, 'Заказ на сборке'), (3, 'Передан курьеру')], db_index=True, default=0, verbose_name='Статус заказа'),
        ),
    ]
