# Generated by Django 3.2.15 on 2024-03-21 12:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240321_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес заказа'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер 📳'),
        ),
    ]
