# Generated by Django 3.2.15 on 2024-03-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20240321_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='comments',
            new_name='comment',
        ),
    ]
