# Generated by Django 3.2.15 on 2024-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20240322_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='call_date',
            field=models.DateTimeField(editable=False, help_text='Дата звонка', verbose_name='Созвон'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delivered_date',
            field=models.DateTimeField(editable=False, help_text='Дата доставки', verbose_name='Доставка'),
        ),
    ]
