# Generated by Django 3.2.15 on 2024-03-22 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20240322_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payment',
            field=models.BooleanField(choices=[(False, 'Наличные'), (True, 'Электронно')], db_index=True, default=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='call_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Дата звонка', verbose_name='Созвон'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Дата доставки', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='registr_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата регистрации заказа', verbose_name='Заказ'),
        ),
    ]
