# Generated by Django 3.2.15 on 2024-03-22 10:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20240322_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='call_date',
            field=models.DateTimeField(blank=True, help_text='Дата звонка', verbose_name='Созвон'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, help_text='Дата доставки', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment',
            field=models.BooleanField(choices=[(False, '💰'), (True, '💳')], db_index=True, default=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='-', max_length=128, null=True, region='RU', verbose_name='Номер 📳'),
        ),
    ]
