# Generated by Django 3.2.15 on 2024-03-22 14:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20240322_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, to='foodcartapp.Restaurant', verbose_name='доступные рестораны'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='-', max_length=128, null=True, region='RU', verbose_name='Номер ☎️'),
        ),
    ]
