# Generated by Django 3.2.15 on 2024-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20240322_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='Кол-во заказа'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='foodcartapp.Restaurant', verbose_name='доступные рестораны'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment',
            field=models.BooleanField(choices=[(False, 'Наличные'), (True, 'Оплата картой')], db_index=True, default=True, verbose_name='Оплата'),
        ),
    ]
