# Generated by Django 3.2.15 on 2024-04-17 13:59

from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, default=foodcartapp.models.allRestaurant, null=True, to='foodcartapp.Restaurant', verbose_name='доступные рестораны'),
        ),
    ]
