# Generated by Django 3.2.15 on 2024-04-25 11:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_alter_userorder_available_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во заказа'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='call_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата звонка', null=True, verbose_name='Созвон'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата доставки', null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер ☎️'),
        ),
    ]
